
name: Mirror Git

on:
  workflow_dispatch:
   inputs:
      android:
        description: 'Whether to trigger an Android build (true/false/auto)'
        required: false
        default: 'true'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Clone GitLab repo
      run: |
        git clone --branch android https://github.com/murderlandsgame/Cemu-Android-sorry mirror

    - name: Copy GitHub Action file to cloned repo
      run: |
        mkdir -p mirror/.github/workflows/
        cp .github/workflows/mirror.yml mirror/.github/workflows/
        cp .github/workflows/android_build.yml mirror/.github/workflows/
        cp .github/workflows/android_build_two.yml mirror/.github/workflows/
        cp .github/workflows/build_check.yml mirror/.github/workflows/
        cp .github/workflows/build.yml mirror/.github/workflows/
        cp .github/workflows/deploy_experimental_release.yml mirror/.github/workflows/
        cp .github/workflows/deploy_stable_release.yml mirror/.github/workflows/
        cp .github/workflows/determine_release_version.yml mirror/.github/workflows/
        cp .github/workflows/generate_pot.yml mirror/.github/workflows/
        
